/*
 * Loads the generated models and adds what the database itself doesn't describe.
 * Everything else in this folder is generated by `npm run db:generate-models`; keep
 * hand-written changes in this file so regeneration never loses them.
 */
const { sequelize } = require('../config/database');
const initModels = require('./init-models');

const models = initModels(sequelize);

const {
  Drivers,
  DriverRateHistory,
  SubVendorAttendance,
  SubVendorCharges,
  SubVendorDailyLogs,
  SubVendorDriverRateHistory,
  SubVendorDrivers,
  SubVendorFuelLogs,
  SubVendorMaintenance,
  SubVendorRoutes,
  SubVendorSalaryTransactions,
  SubVendorVehicles,
} = models;

// --- Associations with no foreign key in the database --------------------------------
// Aliases match the generated own-fleet ones ("driver", "vehicle") so the same
// `include` works for both scopes. constraints:false because the FKs don't exist.
const noFk = { constraints: false };

DriverRateHistory.belongsTo(Drivers, { as: 'driver', foreignKey: 'driver_id', ...noFk });
Drivers.hasMany(DriverRateHistory, { as: 'rate_history', foreignKey: 'driver_id', ...noFk });

SubVendorDriverRateHistory.belongsTo(SubVendorDrivers, { as: 'driver', foreignKey: 'driver_id', ...noFk });
SubVendorDrivers.hasMany(SubVendorDriverRateHistory, { as: 'rate_history', foreignKey: 'driver_id', ...noFk });

SubVendorAttendance.belongsTo(SubVendorDrivers, { as: 'driver', foreignKey: 'driver_id', ...noFk });
SubVendorDrivers.hasMany(SubVendorAttendance, { as: 'attendances', foreignKey: 'driver_id', ...noFk });

SubVendorSalaryTransactions.belongsTo(SubVendorDrivers, { as: 'driver', foreignKey: 'driver_id', ...noFk });
SubVendorDrivers.hasMany(SubVendorSalaryTransactions, { as: 'salary_transactions', foreignKey: 'driver_id', ...noFk });

SubVendorDailyLogs.belongsTo(SubVendorDrivers, { as: 'driver', foreignKey: 'driver_id', ...noFk });
SubVendorDrivers.hasMany(SubVendorDailyLogs, { as: 'daily_logs', foreignKey: 'driver_id', ...noFk });
SubVendorDailyLogs.belongsTo(SubVendorVehicles, { as: 'vehicle', foreignKey: 'vehicle_id', ...noFk });
SubVendorVehicles.hasMany(SubVendorDailyLogs, { as: 'daily_logs', foreignKey: 'vehicle_id', ...noFk });

SubVendorRoutes.belongsTo(SubVendorDrivers, { as: 'driver', foreignKey: 'driver_id', ...noFk });
SubVendorDrivers.hasMany(SubVendorRoutes, { as: 'routes', foreignKey: 'driver_id', ...noFk });
SubVendorRoutes.belongsTo(SubVendorVehicles, { as: 'vehicle', foreignKey: 'vehicle_id', ...noFk });
SubVendorVehicles.hasMany(SubVendorRoutes, { as: 'routes', foreignKey: 'vehicle_id', ...noFk });

SubVendorFuelLogs.belongsTo(SubVendorVehicles, { as: 'vehicle', foreignKey: 'vehicle_id', ...noFk });
SubVendorVehicles.hasMany(SubVendorFuelLogs, { as: 'fuel_logs', foreignKey: 'vehicle_id', ...noFk });

SubVendorMaintenance.belongsTo(SubVendorVehicles, { as: 'vehicle', foreignKey: 'vehicle_id', ...noFk });
SubVendorVehicles.hasMany(SubVendorMaintenance, { as: 'maintenances', foreignKey: 'vehicle_id', ...noFk });

SubVendorCharges.belongsTo(SubVendorVehicles, { as: 'vehicle', foreignKey: 'vehicle_id', ...noFk });
SubVendorVehicles.hasMany(SubVendorCharges, { as: 'charges', foreignKey: 'vehicle_id', ...noFk });

// --- Generated (computed) columns: readable, never written ---------------------------
// MySQL computes these (GENERATED ALWAYS AS ... STORED) and rejects any value for them.
const GENERATED_COLUMNS = {
  DailyLogs: ['total_km', 'profit'],
};

function protectGeneratedColumns(model, columns) {
  const isWritable = (field) => !columns.includes(field);

  model.addHook('beforeSave', (instance, options) => {
    for (const col of columns) delete instance.dataValues[col];
    if (options.fields) options.fields = options.fields.filter(isWritable);
  });
  model.addHook('beforeBulkCreate', (instances, options) => {
    for (const instance of instances) for (const col of columns) delete instance.dataValues[col];
    if (options.fields) options.fields = options.fields.filter(isWritable);
  });
  model.addHook('beforeBulkUpdate', (options) => {
    for (const col of columns) delete options.attributes[col];
    if (options.fields) options.fields = options.fields.filter(isWritable);
  });
}

for (const [name, columns] of Object.entries(GENERATED_COLUMNS)) {
  protectGeneratedColumns(models[name], columns);
}

// --- Ids that are AUTO_INCREMENT in production -----------------------------------------
// The production dump (2 Oct 2026) has AUTO_INCREMENT on these ids; the older car_tracking dump
// the models were generated from does not, so the generated models lack it.
// (sub_vendor_attendance.id has none in production either; attendance.service assigns ids.)
for (const name of ['SubVendorDrivers', 'SubVendorDriverRateHistory']) {
  const attr = models[name].rawAttributes.id;
  if (!attr.autoIncrement) {
    attr.autoIncrement = true;
    models[name].refreshAttributes();
    models[name].autoIncrementAttribute = 'id'; // so the insert id is read back after create()
  }
}

module.exports = { sequelize, models, GENERATED_COLUMNS };
